### PR TITLE
 DetoxSync: add fishhook as submodule.

### PR DESCRIPTION
**Pull request by asafkorem**
Depends on https://github.com/wix/DTXObjectiveCHelpers/pull/2.

### CODE REVIEW

**Review by d4vidi — COMMENTED** [review]
As for `DTXObjectiveCHelpers`' commit - better to use `1f1b380775f604c61ec4eb8584df40f1d8487291` (i.e. the one generated in `master` following the merge).

**Comment by asafkorem** [comment]
> As for `DTXObjectiveCHelpers`' commit - better to use `1f1b380775f604c61ec4eb8584df40f1d8487291` (i.e. the one generated in `master` following the merge).

Good point, doing it :+1:

> @asafkorem seems that the submodule, though named `DTXSwizzlingHelper`, is in fact wired to `DTXObjectiveCHelpers` as its remote. Would you consider a rename?

That's true, I thought about this too, but I generally think that we should migrate all these sub-projects into the main project repo. 
Anyway, until then, I agree that it would be better to rename it. I'll add this.

**Comment by d4vidi** [comment]
I see your point 🆗

**Comment by asafkorem** [comment]
Done 🙂

**Pull request merged**
